### ISSUE TITLE
prebuild binray?

### ISSUE THREAD

**Issue by omaru-ok** [vim-zz/swordfish-rs#3]
it would be nice to have binary rather cargo . since im not a rust dev :(

**Comment by vim-zz** [comment]
Here you go [releases](https://github.com/vim-zz/swordfish-rs/releases)

On Mac you'll need to allow “Open an app from an unidentified developer” for this app. You can follow these instructions:

https://support.apple.com/en-il/guide/mac-help/mh40616/mac

or 

https://apple.stackexchange.com/questions/202169/how-can-i-open-an-app-from-an-unidentified-developer-without-using-the-gui
